<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\Permission\Traits\HasRoles;

class PatientMedicalRecord extends Model
{
    use HasFactory, HasRoles;

    protected $fillable = [
        'mrn',
        'patient_id',
        'doctor_id',
        'symptoms',
        'symptoms_other',
        'history',
        'diagnosis',
        'doctor_recommondations',
        'signs',
        'vision_od_img1',
        'vision_os_img1',
        'vision_od_img2',
        'vision_os_img2',
        'vision_od_img3',
        'vision_os_img3',
        'vision_od_img4',
        'vision_os_img4',
        'sel_1_od',
        'sel_1_os',
        'sel_2_od',
        'sel_2_os',
        'sel_3_od',
        'sel_3_os',
        'sel_4_od',
        'sel_4_os',
        'sel_5_od',
        'sel_5_os',
        'sel_6_od',
        'sel_6_os',
        'sel_7_od',
        'sel_7_os',
        'sel_8_od',
        'sel_8_os',
        'sel_9_od',
        'sel_9_os',
        'sel_10_od',
        'sel_10_os',
        'sel_11_od',
        'sel_11_os',
        'sel_12_od',
        'sel_12_os',
        'sel_13_od',
        'sel_13_os',
        'sel_14_od',
        'sel_14_os',
        'od_disc_margins',
        'os_disc_margins',
        'od_cdr',
        'os_cdr',
        'od_nrr',
        'os_nrr',
        'od_av_ratio',
        'os_av_ratio',
        'od_fr',
        'os_fr',
        'od_periphery',
        'os_periphery',
        'gonio_od_top',
        'gonio_od_right',
        'gonio_od_bottom',
        'gonio_od_left',
        'gonio_od',
        'gonio_os_top',
        'gonio_os_right',
        'gonio_os_bottom',
        'gonio_os_left',
        'gonio_os',
        'review_date',
        'created_by',
        'is_patient_admission',
        'is_patient_surgery',
    ];
}
